x-redis-common: &redis_common
  image: &redis_image redis:5.0.6-alpine
  command: redis-server /etc/redis/redis.conf
  network_mode: "host"
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]

services:
  redis-1:
    <<: *redis_common
    container_name: "redis-1"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7001", "ping"]
    volumes:
      - "./7001/conf/redis.conf:/etc/redis/redis.conf"
      - "./7001/data:/data"

  redis-2:
    <<: *redis_common
    container_name: "redis-2"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7002", "ping"]
    volumes:
      - "./7002/conf/redis.conf:/etc/redis/redis.conf"
      - "./7002/data:/data"

  redis-3:
    <<: *redis_common
    container_name: "redis-3"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7003", "ping"]
    volumes:
      - "./7003/conf/redis.conf:/etc/redis/redis.conf"
      - "./7003/data:/data"

  redis-4:
    <<: *redis_common
    container_name: "redis-4"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7004", "ping"]
    volumes:
      - "./7004/conf/redis.conf:/etc/redis/redis.conf"
      - "./7004/data:/data"

  redis-5:
    <<: *redis_common
    container_name: "redis-5"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7005", "ping"]
    volumes:
      - "./7005/conf/redis.conf:/etc/redis/redis.conf"
      - "./7005/data:/data"

  redis-6:
    <<: *redis_common
    container_name: "redis-6"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "7006", "ping"]
    volumes:
      - "./7006/conf/redis.conf:/etc/redis/redis.conf"
      - "./7006/data:/data"

  redis-cluster-entry:
    container_name: "redis-cluster-entry"
    image: *redis_image
    network_mode: "host"
    command: >
      sh -c "
        echo 'Waiting for Redis nodes to be ready...';
        sleep 10;
        echo 'Creating cluster with localhost IPs for external access...';
        redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-replicas 1 --cluster-yes
      "
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

  p3x-redis-ui:
    image: patrikx3/p3x-redis-ui:2025.4.136
    restart: always
    container_name: p3x-redis-ui
    ports:
      - "7843:7843"
    volumes:
      - ./p3x-conf:/settings
    networks:
      - dev_net
      
networks:
  dev_net:
    external: true